pipeline:
  dirs:
    image: alpine
    commands:
      - mkdir -p out/layout
      - mkdir -p out/bom/interactive
      - mkdir -p out/schematic
      - mkdir -p revs/heads

  bom:
    image: kicad-automation:4layers
    group: fabrication-outputs
    commands:
      - python -m kicad-automation.eeschema.export_bom --schematic hardware/licheedmi/licheedmi.sch --output_dir out/bom export
      - mv out/bom/bom.csv out/bom/licheedmi-bom.csv
      - python -m kicad-automation.eeschema.export_bom --schematic hardware/hdmizness/hdmizness.sch --output_dir out/bom export
      - mv out/bom/bom.csv out/bom/hdmizness-bom.csv

  ibom:
    image: kicad-automation:4layers
    group: fabrication-outputs
    commands:
      - sh /opt/InteractiveHtmlBom/make-interactive-bom hardware/licheedmi/licheedmi.kicad_pcb
      - mv /output/bom/interactive/ibom.html out/bom/licheedmi-ibom.csv
      - sh /opt/InteractiveHtmlBom/make-interactive-bom hardware/hdmizness/hdmizness.kicad_pcb
      - mv /output/bom/interactive/ibom.html out/bom/hdmizness-ibom.csv

  schematic-licheedmi:
    image: kicad-automation:4layers
    group: fabrication-outputs
    commands:
      - python -m kicad-automation.eeschema.schematic --schematic hardware/licheedmi/licheedmi.sch --output_dir out/schematic export --all_pages -f pdf

  schematic-hdmizness:
    image: kicad-automation:2layers
    group: fabrication-outputs
    commands:
      - python -m kicad-automation.eeschema.schematic --schematic hardware/hdmizness/hdmizness.sch --output_dir out/schematic export --all_pages -f pdf

  gerbers-licheedmi:
    image: kicad-automation:4layers
    group: fabrication-outputs
    commands:
      - kiplot -b hardware/licheedmi/licheedmi.kicad_pcb -c /opt/etc/kiplot/generic_plot.kiplot.yaml -v -d out

  gerbers-hdmizness:
    image: kicad-automation:4layers
    group: fabrication-outputs
    commands:
      - kiplot -b hardware/hdmizness/hdmizness.kicad_pcb -c /opt/etc/kiplot/generic_plot.kiplot.yaml -v -d out

  zip-gerbers-licheedmi:
    image: kramos/alpine-zip
    commands:
      - cd out/layout/gerber
      - zip licheedmi.zip licheedmi-*_Cu.gbr licheedmi-*_Mask.gbr licheedmi-*_Paste.gbr licheedmi-*_SilkS.gbr licheedmi-*Edge_Cuts.gbr licheedmi-*-drl.gbr

  zip-gerbers-hdmizness:
    image: kramos/alpine-zip
    commands:
      - cd out/layout/gerber
      - zip hdmizness.zip hdmizness-*_Cu.gbr hdmizness-*_Mask.gbr hdmizness-*_Paste.gbr hdmizness-*_SilkS.gbr hdmizness-*Edge_Cuts.gbr hdmizness-*-drl.gbr

  revs:
    image: alpine
    group: revs
    commands:
      - '[[ ${DRONE_TAG} == "" ]] && cp -r out revs/heads/${DRONE_BRANCH} || true'
      - '[[ "${DRONE_BRANCH}" == "master" ]] && cp -r out revs/latest || true'
      - 'if [[ "${DRONE_TAG}" != "" ]]; then mkdir -p revs/tags; cp -r out revs/tags/${DRONE_TAG}; fi'

  upload:
    image: plugins/s3
    endpoint: https://drone.s3.vps4.tuetuopay.fr
    bucket: hdmizness
    source: revs/**/*
    target: /
    path_style: true
    strip_prefix: revs
    secrets: [plugin_access_key, plugin_secret_key]
